[pytest]
addopts =
    -v
    --tb=short
    --headed
    --slowmo=500
    --html=reports/test_report.html
    --self-contained-html
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*